package bank.database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Database {

    private static final String URL =
            "jdbc:h2:./data/bankdb";

    private static final String USER = "sa";
    private static final String PASSWORD = "";

    public static Connection getConnection()
            throws SQLException {

        return DriverManager.getConnection(
                URL,
                USER,
                PASSWORD
        );
    }

    public static void createTables() {

        String customersTable = """
                CREATE TABLE IF NOT EXISTS customers (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(50),
                    surname VARCHAR(50),
                    email VARCHAR(100) UNIQUE
                )
                """;

        String accountsTable = """
                CREATE TABLE IF NOT EXISTS accounts (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id INT,
                    deposit1_number VARCHAR(50),
                    deposit2_number VARCHAR(50),
                    deposit1_balance DECIMAL(19,2) DEFAULT 0,
                    deposit2_balance DECIMAL(19,2) DEFAULT 0,
                    
                    deposit1_rate DECIMAL(5,2),
                    deposit1_term_months INT,
                    deposit1_open_date DATE,
                    deposit1_end_date DATE,
                    deposit1_simulated_months INT DEFAULT 0,
                    deposit1_reward DECIMAL(19,2) DEFAULT 0,
                    
                    deposit2_rate DECIMAL(5,2),
                    deposit2_term_months INT,
                    deposit2_open_date DATE,
                    deposit2_end_date DATE,
                    deposit2_simulated_months INT DEFAULT 0,
                    deposit2_reward DECIMAL(19,2) DEFAULT 0,
                    
                    FOREIGN KEY (customer_id) REFERENCES customers(id)
                )
                """;

        String transactionsTable = """
                CREATE TABLE IF NOT EXISTS transactions (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    account_id INT,
                    amount DECIMAL(19,2),
                    type VARCHAR(50),
                    transaction_time TIMESTAMP,
                    FOREIGN KEY (account_id) REFERENCES accounts(id)
                )
                """;

        try (
                Connection connection = getConnection();
                Statement statement =
                        connection.createStatement()
        ) {

            statement.execute(customersTable);
            statement.execute(accountsTable);
            statement.execute(transactionsTable);

            System.out.println(
                    "Таблицы базы данных созданы."
            );

        } catch (SQLException e) {

            System.out.println(
                    "Ошибка базы данных: "
                            + e.getMessage()
            );
        }
    }
}